-- Generated by Unity Splice Content Catalog Exporter. Do not edit by hand.
BEGIN;
INSERT INTO splice.content_definitions
  (content_id, faction_id, content_kind, defense_capacity_cost, gold_cost, enabled, content_version) VALUES
  ('1/0','1','MINER',0,10,true,'content-c3-v1'),
  ('1/1','1','GARRISON',1,4,true,'content-c3-v1'),
  ('1/1','1','TOWER',2,10,true,'content-c3-v1'),
  ('1/2','1','GARRISON',2,5,true,'content-c3-v1'),
  ('1/3','1','GARRISON',2,10,true,'content-c3-v1'),
  ('1/4','1','GARRISON',2,4,true,'content-c3-v1')
ON CONFLICT (content_id, content_kind) DO UPDATE SET
  faction_id=EXCLUDED.faction_id,
  defense_capacity_cost=EXCLUDED.defense_capacity_cost, gold_cost=EXCLUDED.gold_cost,
  enabled=true, content_version=EXCLUDED.content_version;
COMMIT;
