using System;
using System.Collections.Generic;
using UnityEngine;

namespace Splice.FxStudio
{
    [Serializable]
    public sealed class SpliceFxStageBinding
    {
        public SpliceFxStage stage;
        public string customMarker;
        public SpliceFxBlendSequence sequence;
        [Tooltip("Generated by the exporter. Do not hand-edit this prefab.")]
        public GameObject exportedPrefab;
        [Min(0f)] public float delaySeconds;
        public SpliceFxPlacement placement = SpliceFxPlacement.WorldPoint;
        public SpliceFxScaleMode scaleMode = SpliceFxScaleMode.HeroRelative;
        public Vector3 localOffset;
        [Min(0f)] public float groundOffset = 0.05f;
        public bool orientToDirection = true;

        public float LifetimeSeconds =>
            sequence != null ? Mathf.Max(0.05f, sequence.DurationSeconds) : 1f;
    }

    [CreateAssetMenu(fileName = "SkillFxPackage",
        menuName = "Splice/FX Studio/Skill FX Package")]
    public sealed class SpliceFxSkillPackage : ScriptableObject
    {
        public string packageId = "new_skill_fx";
        public string displayName = "New Skill FX";
        [Min(1)] public int schemaVersion = 1;
        public List<SpliceFxStageBinding> stages = new();

        public bool HasConfiguredStage
        {
            get
            {
                foreach (var binding in stages)
                    if (binding?.exportedPrefab != null)
                        return true;
                return false;
            }
        }

        public SpliceFxStageBinding Find(SpliceFxStage stage,
            string customMarker = null)
        {
            foreach (var binding in stages)
            {
                if (binding == null || binding.stage != stage) continue;
                if (stage != SpliceFxStage.Custom ||
                    string.Equals(binding.customMarker, customMarker,
                        StringComparison.Ordinal))
                    return binding;
            }
            return null;
        }

        private void OnValidate()
        {
            packageId = SpliceFxPresetDefinition.SanitizeId(packageId);
            schemaVersion = Mathf.Max(1, schemaVersion);
        }
    }
}
