using System.Collections.Generic;
using UnityEngine;

namespace Splice.FxStudio
{
    [CreateAssetMenu(fileName = "SubFx",
        menuName = "Splice/FX Studio/SubFX")]
    public sealed class SpliceFxSubEffectDefinition : ScriptableObject
    {
        [Header("Identity")]
        public string subFxId = "new_sub_fx";
        public string displayName = "New SubFX";
        [Min(1)] public int schemaVersion = 2;

        [Header("Preset")]
        public SpliceFxPresetDefinition preset;
        [Tooltip("Optional one-off override. Leave empty to use the preset template.")]
        public GameObject templateOverride;
        public SpliceFxElementStyle elementStyle;
        [HideInInspector]
        public SpliceFxMotionModifier motionModifiers;

        [Header("FX Motion Stack")]
        [Tooltip("Motions are evaluated from top to bottom and can be blended together.")]
        public List<SpliceFxMotionLayer> motions = new();

        [Header("Instance Layout")]
        [Tooltip("Duplicate one source visual into a radial, arc, line, grid, random or manual formation.")]
        public SpliceFxInstanceLayout instanceLayout = new();

        [Header("Texture Pipeline")]
        public Texture2D sourceTexture;
        [Tooltip("Generated by Alpha Processor. The source is never overwritten.")]
        public Texture2D processedTexture;
        public SpliceFxAlphaSettings alpha = new();

        [Header("Common Visual Values")]
        public Color mainColor = Color.white;
        public SpliceFxGradientMode gradientMode =
            SpliceFxGradientMode.Solid;
        public Gradient mainGradient = CreateDefaultGradient();
        public bool reverseGradient;
        [Min(0f)] public float emission = 3f;
        [Min(0.01f)] public float lifetime = 1f;
        [Min(0f)] public float spawnRate = 32f;
        [Min(0f)] public float speed = 1f;
        [Min(0.001f)] public float size = 1f;
        [Min(0f)] public float radius = 1f;
        public float rotationSpeed = 30f;
        [Min(0f)] public float noiseStrength;
        public SpliceFxQualityMask quality = SpliceFxQualityMask.All;

        [Header("Stroke / Outline")]
        public SpliceFxStrokeMode strokeMode =
            SpliceFxStrokeMode.None;
        public Color strokeColor =
            new(1f, 0.35f, 0.05f, 1f);
        [Range(0f, 16f)] public float strokeWidth = 2f;
        [Range(1f, 32f)] public float strokeDashFrequency = 8f;

        [Header("Additional Visual Layers")]
        public List<SpliceFxVisualLayerDefinition> visualLayers = new();

        [Header("Custom Exposed Values")]
        public List<SpliceFxPropertyValue> customValues = new();

        public GameObject EffectiveTemplate =>
            templateOverride != null
                ? templateOverride
                : preset != null ? preset.templatePrefab : null;

        public Texture EffectiveTexture =>
            processedTexture != null ? processedTexture : sourceTexture;

        private void OnValidate()
        {
            subFxId = SpliceFxPresetDefinition.SanitizeId(subFxId);
            schemaVersion = Mathf.Max(1, schemaVersion);
            lifetime = Mathf.Max(0.01f, lifetime);
            size = Mathf.Max(0.001f, size);
            if (motions == null) motions = new List<SpliceFxMotionLayer>();
            foreach (var motion in motions)
            {
                if (motion == null) continue;
                motion.amount = Mathf.Max(0f, motion.amount);
                motion.delaySeconds =
                    Mathf.Max(0f, motion.delaySeconds);
                motion.durationSeconds =
                    Mathf.Max(0.01f, motion.durationSeconds);
                if (motion.axis.sqrMagnitude < 0.0001f)
                    motion.axis = Vector3.up;
            }
            mainGradient ??= CreateDefaultGradient();
            visualLayers ??=
                new List<SpliceFxVisualLayerDefinition>();
            foreach (var layer in visualLayers)
            {
                if (layer == null) continue;
                layer.color ??= CreateDefaultGradient();
                layer.emission = Mathf.Max(0f, layer.emission);
                layer.localScale = SanitizeScale(layer.localScale);
                layer.instanceLayout ??= new SpliceFxInstanceLayout();
                layer.motions ??= new List<SpliceFxMotionLayer>();
                foreach (var motion in layer.motions)
                {
                    if (motion == null) continue;
                    motion.amount = Mathf.Max(0f, motion.amount);
                    motion.delaySeconds =
                        Mathf.Max(0f, motion.delaySeconds);
                    motion.durationSeconds =
                        Mathf.Max(0.01f,
                            motion.durationSeconds);
                    if (motion.axis.sqrMagnitude < 0.0001f)
                        motion.axis = Vector3.up;
                }
                layer.trailTime = Mathf.Max(0.01f, layer.trailTime);
                layer.trailStartWidth =
                    Mathf.Max(0.001f, layer.trailStartWidth);
                layer.trailEndWidth =
                    Mathf.Max(0f, layer.trailEndWidth);
                layer.trailMinVertexDistance =
                    Mathf.Max(0.001f,
                        layer.trailMinVertexDistance);
                layer.particleMaxCount =
                    Mathf.Clamp(layer.particleMaxCount, 1, 2048);
                layer.particleRate =
                    Mathf.Max(0f, layer.particleRate);
                layer.particleBurstCount =
                    Mathf.Clamp(layer.particleBurstCount, 1, 512);
                layer.particleLifetime =
                    Mathf.Max(0.01f, layer.particleLifetime);
                layer.particleSpeed =
                    Mathf.Max(0f, layer.particleSpeed);
                layer.particleSize =
                    Mathf.Max(0.001f, layer.particleSize);
                layer.particleShapeRadius =
                    Mathf.Max(0f, layer.particleShapeRadius);
            }
            instanceLayout ??= new SpliceFxInstanceLayout();
            instanceLayout.highCount =
                Mathf.Clamp(instanceLayout.highCount, 1, 64);
            instanceLayout.mediumCount = Mathf.Clamp(
                instanceLayout.mediumCount, 0,
                instanceLayout.highCount);
            instanceLayout.lowCount = Mathf.Clamp(
                instanceLayout.lowCount, 0,
                instanceLayout.highCount);
            if (instanceLayout.planeAxis.sqrMagnitude < 0.0001f)
                instanceLayout.planeAxis = Vector3.up;
            if (instanceLayout.startDirection.sqrMagnitude < 0.0001f)
                instanceLayout.startDirection = Vector3.forward;
            if (instanceLayout.selfSpinAxis.sqrMagnitude < 0.0001f)
                instanceLayout.selfSpinAxis = Vector3.up;
            instanceLayout.activationDelayStep =
                Mathf.Max(0f, instanceLayout.activationDelayStep);
            instanceLayout.activeDuration =
                Mathf.Max(0f, instanceLayout.activeDuration);
        }

        private static Gradient CreateDefaultGradient()
        {
            var result = new Gradient();
            result.SetKeys(
                new[]
                {
                    new GradientColorKey(Color.white, 0f),
                    new GradientColorKey(Color.white, 1f)
                },
                new[]
                {
                    new GradientAlphaKey(1f, 0f),
                    new GradientAlphaKey(1f, 1f)
                });
            return result;
        }

        private static Vector3 SanitizeScale(Vector3 value) =>
            new(Mathf.Max(0.001f, Mathf.Abs(value.x)),
                Mathf.Max(0.001f, Mathf.Abs(value.y)),
                Mathf.Max(0.001f, Mathf.Abs(value.z)));
    }
}
