using System.Collections.Generic;
using UnityEngine;

namespace Splice.FxStudio
{
    [CreateAssetMenu(fileName = "SubFx",
        menuName = "Splice/FX Studio/SubFX")]
    public sealed class SpliceFxSubEffectDefinition : ScriptableObject
    {
        [Header("Identity")]
        public string subFxId = "new_sub_fx";
        public string displayName = "New SubFX";
        [Min(1)] public int schemaVersion = 1;

        [Header("Preset")]
        public SpliceFxPresetDefinition preset;
        [Tooltip("Optional one-off override. Leave empty to use the preset template.")]
        public GameObject templateOverride;
        public SpliceFxElementStyle elementStyle;
        [HideInInspector]
        public SpliceFxMotionModifier motionModifiers;

        [Header("FX Motion Stack")]
        [Tooltip("Motions are evaluated from top to bottom and can be blended together.")]
        public List<SpliceFxMotionLayer> motions = new();

        [Header("Texture Pipeline")]
        public Texture2D sourceTexture;
        [Tooltip("Generated by Alpha Processor. The source is never overwritten.")]
        public Texture2D processedTexture;
        public SpliceFxAlphaSettings alpha = new();

        [Header("Common Visual Values")]
        public Color mainColor = Color.white;
        [Min(0f)] public float emission = 3f;
        [Min(0.01f)] public float lifetime = 1f;
        [Min(0f)] public float spawnRate = 32f;
        [Min(0f)] public float speed = 1f;
        [Min(0.001f)] public float size = 1f;
        [Min(0f)] public float radius = 1f;
        public float rotationSpeed = 30f;
        [Min(0f)] public float noiseStrength;
        public SpliceFxQualityMask quality = SpliceFxQualityMask.All;

        [Header("Custom Exposed Values")]
        public List<SpliceFxPropertyValue> customValues = new();

        public GameObject EffectiveTemplate =>
            templateOverride != null
                ? templateOverride
                : preset != null ? preset.templatePrefab : null;

        public Texture EffectiveTexture =>
            processedTexture != null ? processedTexture : sourceTexture;

        private void OnValidate()
        {
            subFxId = SpliceFxPresetDefinition.SanitizeId(subFxId);
            schemaVersion = Mathf.Max(1, schemaVersion);
            lifetime = Mathf.Max(0.01f, lifetime);
            size = Mathf.Max(0.001f, size);
            if (motions == null) motions = new List<SpliceFxMotionLayer>();
            foreach (var motion in motions)
            {
                if (motion == null) continue;
                motion.amount = Mathf.Max(0f, motion.amount);
                motion.delaySeconds =
                    Mathf.Max(0f, motion.delaySeconds);
                motion.durationSeconds =
                    Mathf.Max(0.01f, motion.durationSeconds);
                if (motion.axis.sqrMagnitude < 0.0001f)
                    motion.axis = Vector3.up;
            }
        }
    }
}
